apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort # Ou LoadBalancer selon votre besoin
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000 # Par exemple, pour un accès via NodePort
  selector:
    app: wordpress
